package com.example.managerfeedback.util;

public enum ECategory {
    CATEGORY_HOMEPAGE,
    CATEGORY_POLITICAL,
    CATEGORY_SOCIAL,
    CATEGORY_ECONOMY,
    CATEGORY_HEALTH,
    CATEGORY_EDUCATION,
    CATEGORY_LAW,
    CATEGORY_SPORT,
    CATEGORY_WORLD
}
